import {
  Gym,
  Branch,
  UserProfile,
  Member,
  MembershipPlan,
  MemberMembership,
  AttendanceRecord,
  PaymentRecord,
  ExpenseRecord,
  Trainer,
  WorkoutPlan,
  DietPlan,
  ProgressRecord,
  PTSession,
  InventoryItem,
  EquipmentItem,
  NotificationItem,
  AutomationRule,
  AuditLog,
  UserRole,
} from './types'

export const INITIAL_GYM: Gym = {
  id: 'gym_01',
  name: 'The Power Fitness Zone',
  logo_url: '/logo.png',
  address: 'Plot 42, Fitness Avenue, Near Central Park',
  city: 'Ahmedabad',
  state: 'Gujarat',
  zip_code: '380015',
  phone: '+91 98765 43210',
  email: 'contact@powerfitnesszone.com',
  opening_hours: '06:00 AM - 10:00 PM (Mon-Sat)',
  currency: 'INR',
  timezone: 'Asia/Kolkata',
  gst_registered: true,
  gstin: '24AAACG1234F1Z5',
  cgst_rate: 9,
  sgst_rate: 9,
  primary_color: '#6C5CE7',
  invoice_prefix: 'TPFZ/2026-27/',
  member_prefix: 'TPFZ-M-',
  grace_days: 2,
  created_at: '2026-01-01T00:00:00Z',
}

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'br_01',
    gym_id: 'gym_01',
    name: 'Main Branch (Satellite)',
    address: 'Plot 42, Fitness Avenue, Satellite, Ahmedabad',
    phone: '+91 98765 43210',
    is_main: true,
  },
  {
    id: 'br_02',
    gym_id: 'gym_01',
    name: 'Downtown Branch (Bodakdev)',
    address: 'Suite 204, Highstreet Plaza, Bodakdev, Ahmedabad',
    phone: '+91 98765 43211',
    is_main: false,
  },
]

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user_owner',
    email: 'owner@powerfitnesszone.com',
    full_name: 'Rahul Sharma',
    phone: '+91 98250 11111',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    role: 'owner',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_manager',
    email: 'manager@powerfitnesszone.com',
    full_name: 'Vikram Patel',
    phone: '+91 98250 22222',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    role: 'branch_manager',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_receptionist',
    email: 'reception@powerfitnesszone.com',
    full_name: 'Neha Gupta',
    phone: '+91 98250 33333',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    role: 'receptionist',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_trainer',
    email: 'trainer@powerfitnesszone.com',
    full_name: 'Rajesh Kumar',
    phone: '+91 98250 44444',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    role: 'trainer',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_nutritionist',
    email: 'nutrition@powerfitnesszone.com',
    full_name: 'Dr. Ananya Singh',
    phone: '+91 98250 55555',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    role: 'nutritionist',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_accountant',
    email: 'accountant@powerfitnesszone.com',
    full_name: 'Suresh Mehta',
    phone: '+91 98250 66666',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    role: 'accountant',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
  {
    id: 'user_member',
    email: 'member@powerfitnesszone.com',
    full_name: 'Amit Verma',
    phone: '+91 98250 77777',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    role: 'member',
    gym_id: 'gym_01',
    branch_id: 'br_01',
  },
]

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem_01',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_code: 'TPFZ-M-0001',
    full_name: 'Amit Verma',
    photo_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    gender: 'male',
    dob: '1995-04-12',
    phone: '+91 98250 77777',
    email: 'member@powerfitnesszone.com',
    address: '402 Sunrise Apartments, Satellite',
    emergency_name: 'Ramesh Verma',
    emergency_phone: '+91 98250 99999',
    joining_date: '2026-01-10',
    source: 'Instagram',
    assigned_trainer_id: 'tr_01',
    assigned_trainer_name: 'Rajesh Kumar',
    status: 'active',
    health_notes: 'Mild lower back sensitivity. Recommended core strengthening.',
    fitness_goals: ['Muscle Gain', 'Fat Loss', 'Stamina'],
    preferred_workout_time: 'Morning (07:00 AM)',
    qr_token: 'QR_AMIT_VERMA_9825077777',
    user_id: 'user_member',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'mem_02',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_code: 'TPFZ-M-0002',
    full_name: 'Priya Joshi',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    gender: 'female',
    dob: '1998-08-22',
    phone: '+91 98251 11222',
    email: 'priya.j@gmail.com',
    address: '12 Green Park Society, Bodakdev',
    emergency_name: 'Ketan Joshi',
    emergency_phone: '+91 98251 11333',
    joining_date: '2026-02-01',
    source: 'Walk-in',
    assigned_trainer_id: 'tr_02',
    assigned_trainer_name: 'Sneha Shah',
    status: 'active',
    health_notes: 'None reported.',
    fitness_goals: ['Weight Loss', 'Flexibility'],
    preferred_workout_time: 'Evening (06:00 PM)',
    qr_token: 'QR_PRIYA_JOSHI_9825111222',
    created_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 'mem_03',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_code: 'TPFZ-M-0003',
    full_name: 'Rohan Trivedi',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    gender: 'male',
    dob: '1992-11-05',
    phone: '+91 98252 33444',
    email: 'rohan.trivedi@outlook.com',
    address: '88 Heritage Tower, Vastrapur',
    emergency_name: 'Sunil Trivedi',
    emergency_phone: '+91 98252 33555',
    joining_date: '2026-03-15',
    source: 'Friend Referral',
    assigned_trainer_id: 'tr_01',
    assigned_trainer_name: 'Rajesh Kumar',
    status: 'active', // Expiring soon in 3 days
    health_notes: 'Right knee rehab completed.',
    fitness_goals: ['Hypertrophy', 'Strength'],
    preferred_workout_time: 'Morning (08:00 AM)',
    qr_token: 'QR_ROHAN_TRIVED_9825233444',
    created_at: '2026-03-15T09:30:00Z',
  },
  {
    id: 'mem_04',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_code: 'TPFZ-M-0004',
    full_name: 'Kavita Desai',
    photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    gender: 'female',
    dob: '1990-03-18',
    phone: '+91 98253 44555',
    email: 'kavita.desai@yahoo.com',
    address: 'B-301 Silver Oaks, Thaltej',
    emergency_name: 'Manish Desai',
    emergency_phone: '+91 98253 44666',
    joining_date: '2025-09-01',
    source: 'Google Maps',
    assigned_trainer_id: 'tr_02',
    assigned_trainer_name: 'Sneha Shah',
    status: 'expired',
    health_notes: 'None.',
    fitness_goals: ['General Fitness'],
    preferred_workout_time: 'Evening (05:00 PM)',
    qr_token: 'QR_KAVITA_DESAI_9825344555',
    created_at: '2025-09-01T14:00:00Z',
  },
  {
    id: 'mem_05',
    gym_id: 'gym_01',
    branch_id: 'br_02',
    member_code: 'TPFZ-M-0005',
    full_name: 'Hardik Patel',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    gender: 'male',
    dob: '1997-06-30',
    phone: '+91 98254 55666',
    email: 'hardik.p@gmail.com',
    address: '15 Royal Enclave, Bodakdev',
    emergency_name: 'Dinesh Patel',
    emergency_phone: '+91 98254 55777',
    joining_date: '2026-04-01',
    source: 'Flex Billboard',
    assigned_trainer_id: 'tr_03',
    assigned_trainer_name: 'Karan Malhotra',
    status: 'frozen',
    health_notes: 'Temporary medical leave requested.',
    fitness_goals: ['Bodybuilding'],
    preferred_workout_time: 'Morning (06:30 AM)',
    qr_token: 'QR_HARDIK_PATEL_9825455666',
    created_at: '2026-04-01T08:00:00Z',
  },
]

export const INITIAL_PLANS: MembershipPlan[] = [
  {
    id: 'plan_01',
    gym_id: 'gym_01',
    name: 'Monthly Transformation',
    duration_value: 1,
    duration_unit: 'months',
    price_paise: 250000, // ₹2,500
    description: 'Full access to gym equipment, locker facilities, and cardio zone.',
    pt_included: false,
    pt_sessions_count: 0,
    freeze_allowed: false,
    freeze_days: 0,
    status: 'active',
  },
  {
    id: 'plan_02',
    gym_id: 'gym_01',
    name: 'Quarterly Strength Plan',
    duration_value: 3,
    duration_unit: 'months',
    price_paise: 650000, // ₹6,500
    description: '3 months full access + 1 complimentary diet consultation.',
    pt_included: false,
    pt_sessions_count: 0,
    freeze_allowed: true,
    freeze_days: 7,
    status: 'active',
  },
  {
    id: 'plan_03',
    gym_id: 'gym_01',
    name: 'Half-Yearly Endurance Plan',
    duration_value: 6,
    duration_unit: 'months',
    price_paise: 1150000, // ₹11,500
    description: '6 months full access + 15 days freeze allowance + steam bath.',
    pt_included: false,
    pt_sessions_count: 0,
    freeze_allowed: true,
    freeze_days: 15,
    status: 'active',
  },
  {
    id: 'plan_04',
    gym_id: 'gym_01',
    name: 'Annual VIP Gold Membership',
    duration_value: 12,
    duration_unit: 'months',
    price_paise: 1999900, // ₹19,999
    description: '1 year all-access to Satellite & Bodakdev branches + 30 days freeze + 4 PT sessions.',
    pt_included: true,
    pt_sessions_count: 4,
    freeze_allowed: true,
    freeze_days: 30,
    status: 'active',
  },
  {
    id: 'plan_05',
    gym_id: 'gym_01',
    name: 'Personal Training Package (12 Sessions)',
    duration_value: 2,
    duration_unit: 'months',
    price_paise: 1500000, // ₹15,000
    description: '12 one-on-one personal training sessions with certified trainer.',
    pt_included: true,
    pt_sessions_count: 12,
    freeze_allowed: true,
    freeze_days: 14,
    status: 'active',
  },
]

export const INITIAL_MEMBERSHIPS: MemberMembership[] = [
  {
    id: 'ms_01',
    gym_id: 'gym_01',
    member_id: 'mem_01',
    member_name: 'Amit Verma',
    plan_id: 'plan_04',
    plan_name: 'Annual VIP Gold Membership',
    start_date: '2026-01-10',
    end_date: '2027-01-09',
    price_paise: 1999900,
    discount_paise: 100000,
    tax_paise: 341982, // 18% GST on base
    final_amount_paise: 2241882,
    payment_status: 'paid',
    status: 'active',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'ms_02',
    gym_id: 'gym_01',
    member_id: 'mem_02',
    member_name: 'Priya Joshi',
    plan_id: 'plan_02',
    plan_name: 'Quarterly Strength Plan',
    start_date: '2026-02-01',
    end_date: '2026-04-30',
    price_paise: 650000,
    discount_paise: 50000,
    tax_paise: 108000,
    final_amount_paise: 708000,
    payment_status: 'paid',
    status: 'active',
    created_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 'ms_03',
    gym_id: 'gym_01',
    member_id: 'mem_03',
    member_name: 'Rohan Trivedi',
    plan_id: 'plan_01',
    plan_name: 'Monthly Transformation',
    start_date: '2026-08-27',
    end_date: '2026-09-26', // Expiring in 2 days
    price_paise: 250000,
    discount_paise: 0,
    tax_paise: 45000,
    final_amount_paise: 295000,
    payment_status: 'paid',
    status: 'active',
    created_at: '2026-08-27T09:30:00Z',
  },
  {
    id: 'ms_04',
    gym_id: 'gym_01',
    member_id: 'mem_04',
    member_name: 'Kavita Desai',
    plan_id: 'plan_01',
    plan_name: 'Monthly Transformation',
    start_date: '2026-07-01',
    end_date: '2026-07-31',
    price_paise: 250000,
    discount_paise: 0,
    tax_paise: 45000,
    final_amount_paise: 295000,
    payment_status: 'paid',
    status: 'expired',
    created_at: '2026-07-01T14:00:00Z',
  },
]

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att_01',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_id: 'mem_01',
    member_name: 'Amit Verma',
    member_code: 'TPFZ-M-0001',
    member_photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    check_in: '2026-09-24T07:15:00Z',
    check_out: '2026-09-24T08:30:00Z',
    method: 'qr_scan',
    is_grace: false,
    auto_closed: false,
    date: '2026-09-24',
  },
  {
    id: 'att_02',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_id: 'mem_02',
    member_name: 'Priya Joshi',
    member_code: 'TPFZ-M-0002',
    member_photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    check_in: '2026-09-24T08:00:00Z',
    method: 'phone_search',
    is_grace: false,
    auto_closed: false,
    date: '2026-09-24',
  },
  {
    id: 'att_03',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    member_id: 'mem_03',
    member_name: 'Rohan Trivedi',
    member_code: 'TPFZ-M-0003',
    member_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    check_in: '2026-09-24T08:45:00Z',
    method: 'qr_scan',
    is_grace: false,
    auto_closed: false,
    date: '2026-09-24',
  },
]

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay_01',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    invoice_number: 'TPFZ/2026-27/0001',
    member_id: 'mem_01',
    member_name: 'Amit Verma',
    membership_id: 'ms_01',
    amount_paise: 1999900,
    discount_paise: 100000,
    tax_paise: 341982,
    final_paise: 2241882,
    paid_paise: 2241882,
    due_paise: 0,
    payment_method: 'upi',
    transaction_ref: 'UPI/626491028374',
    payment_date: '2026-01-10T10:05:00Z',
    collected_by: 'Neha Gupta',
    status: 'paid',
    notes: 'Paid via GPay UPI.',
  },
  {
    id: 'pay_02',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    invoice_number: 'TPFZ/2026-27/0002',
    member_id: 'mem_02',
    member_name: 'Priya Joshi',
    membership_id: 'ms_02',
    amount_paise: 650000,
    discount_paise: 50000,
    tax_paise: 108000,
    final_paise: 708000,
    paid_paise: 500000,
    due_paise: 208000, // Partial payment
    payment_method: 'card',
    transaction_ref: 'HDFC_POS_882190',
    payment_date: '2026-02-01T11:10:00Z',
    collected_by: 'Neha Gupta',
    status: 'partial',
    notes: 'Remaining ₹2,080 due next week.',
  },
]

export const INITIAL_TRAINERS: Trainer[] = [
  {
    id: 'tr_01',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    name: 'Rajesh Kumar',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+91 98250 44444',
    email: 'trainer@powerfitnesszone.com',
    specialization: 'Hypertrophy & Strength Conditioning',
    experience_years: 7,
    joining_date: '2024-03-01',
    salary_paise: 3500000, // ₹35,000 / month
    commission_pct: 15,
    assigned_members_count: 8,
    status: 'active',
  },
  {
    id: 'tr_02',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    name: 'Sneha Shah',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+91 98250 88888',
    email: 'sneha.shah@powerfitnesszone.com',
    specialization: 'CrossFit, Weight Loss & Pilates',
    experience_years: 5,
    joining_date: '2025-01-15',
    salary_paise: 3000000, // ₹30,000 / month
    commission_pct: 12,
    assigned_members_count: 6,
    status: 'active',
  },
  {
    id: 'tr_03',
    gym_id: 'gym_01',
    branch_id: 'br_02',
    name: 'Karan Malhotra',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    phone: '+91 98250 99887',
    email: 'karan.m@powerfitnesszone.com',
    specialization: 'Calisthenics & Bodybuilding',
    experience_years: 6,
    joining_date: '2024-11-10',
    salary_paise: 3200000,
    commission_pct: 15,
    assigned_members_count: 5,
    status: 'active',
  },
]

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp_01',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    category: 'Rent',
    amount_paise: 8500000, // ₹85,000
    date: '2026-09-01',
    vendor: 'Satellite Commercial Complex',
    notes: 'Monthly rent for Satellite branch.',
  },
  {
    id: 'exp_02',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    category: 'Electricity',
    amount_paise: 2800000, // ₹28,000
    date: '2026-09-05',
    vendor: 'Torrent Power',
    notes: 'AC and equipment electricity bill.',
  },
  {
    id: 'exp_03',
    gym_id: 'gym_01',
    branch_id: 'br_01',
    category: 'Equipment Maintenance',
    amount_paise: 650000, // ₹6,500
    date: '2026-09-12',
    vendor: 'FitTech Services',
    notes: 'Treadmill belt replacement.',
  },
]

export const INITIAL_WORKOUTS: WorkoutPlan[] = [
  {
    id: 'wo_01',
    gym_id: 'gym_01',
    member_id: 'mem_01',
    member_name: 'Amit Verma',
    trainer_id: 'tr_01',
    trainer_name: 'Rajesh Kumar',
    name: 'Lean Muscle & Strength 6-Day Hypertrophy',
    goal: 'Muscle Building & Core Stability',
    level: 'intermediate',
    start_date: '2026-09-01',
    end_date: '2026-10-31',
    streak_days: 6,
    exercises: [
      {
        day: 'Monday (Chest & Triceps)',
        list: [
          { id: 'ex_1', name: 'Barbell Bench Press', muscle_group: 'Chest', sets: 4, reps: '8-10', weight_kg: 70, rest_sec: 90, notes: 'Touch chest lightly' },
          { id: 'ex_2', name: 'Incline Dumbbell Press', muscle_group: 'Upper Chest', sets: 3, reps: '10-12', weight_kg: 24, rest_sec: 60 },
          { id: 'ex_3', name: 'Tricep Rope Pushdown', muscle_group: 'Triceps', sets: 4, reps: '12-15', weight_kg: 30, rest_sec: 60 },
        ],
      },
      {
        day: 'Tuesday (Back & Biceps)',
        list: [
          { id: 'ex_4', name: 'Lat Pulldown', muscle_group: 'Lats', sets: 4, reps: '10-12', weight_kg: 55, rest_sec: 90 },
          { id: 'ex_5', name: 'Seated Cable Row', muscle_group: 'Middle Back', sets: 3, reps: '10', weight_kg: 60, rest_sec: 60 },
          { id: 'ex_6', name: 'EZ Bar Bicep Curl', muscle_group: 'Biceps', sets: 4, reps: '12', weight_kg: 20, rest_sec: 60 },
        ],
      },
      {
        day: 'Wednesday (Legs & Glutes)',
        list: [
          { id: 'ex_7', name: 'Barbell Back Squat', muscle_group: 'Quadriceps', sets: 4, reps: '8', weight_kg: 80, rest_sec: 120 },
          { id: 'ex_8', name: 'Leg Extension', muscle_group: 'Quads', sets: 3, reps: '15', weight_kg: 45, rest_sec: 60 },
          { id: 'ex_9', name: 'Hanging Leg Raise', muscle_group: 'Abs', sets: 3, reps: '15', weight_kg: 0, rest_sec: 45 },
        ],
      },
      {
        day: 'Thursday (Shoulders & Traps)',
        list: [
          { id: 'ex_10', name: 'Dumbbell Lateral Raise', muscle_group: 'Shoulders', sets: 4, reps: '12-15', weight_kg: 12, rest_sec: 60 },
          { id: 'ex_11', name: 'Incline Dumbbell Press', muscle_group: 'Shoulders', sets: 4, reps: '10', weight_kg: 22, rest_sec: 90 },
        ],
      },
      {
        day: 'Friday (Arms & Core Power)',
        list: [
          { id: 'ex_12', name: 'EZ Bar Bicep Curl', muscle_group: 'Biceps', sets: 4, reps: '12', weight_kg: 22, rest_sec: 60 },
          { id: 'ex_13', name: 'Tricep Rope Pushdown', muscle_group: 'Triceps', sets: 4, reps: '15', weight_kg: 32, rest_sec: 60 },
          { id: 'ex_14', name: 'Hanging Leg Raise', muscle_group: 'Abs', sets: 4, reps: '20', weight_kg: 0, rest_sec: 45 },
        ],
      },
      {
        day: 'Saturday (Full Body & Cardio)',
        list: [
          { id: 'ex_15', name: 'Barbell Deadlift', muscle_group: 'Back', sets: 4, reps: '6', weight_kg: 100, rest_sec: 120 },
          { id: 'ex_16', name: 'Barbell Bench Press', muscle_group: 'Chest', sets: 3, reps: '10', weight_kg: 65, rest_sec: 90 },
          { id: 'ex_17', name: 'Barbell Back Squat', muscle_group: 'Legs', sets: 3, reps: '10', weight_kg: 70, rest_sec: 90 },
        ],
      },
    ],
  },
]

export const INITIAL_DIETS: DietPlan[] = [
  {
    id: 'dt_01',
    gym_id: 'gym_01',
    member_id: 'mem_01',
    member_name: 'Amit Verma',
    calories_target: 2400,
    protein_g: 160,
    carbs_g: 250,
    fat_g: 65,
    water_liters: 4,
    meals: [
      { name: 'Breakfast', time: '08:30 AM', items: ['4 Egg Whites + 2 Whole Eggs', '100g Oats with Almond Milk', '1 Banana'], calories: 550, completed: true },
      { name: 'Mid-Morning', time: '11:30 AM', items: ['1 Scoop Whey Protein + 10 Almonds'], calories: 220, completed: true },
      { name: 'Lunch', time: '01:30 PM', items: ['150g Grilled Chicken / Paneer', '1.5 Cup Brown Rice', 'Green Salad'], calories: 650, completed: false },
      { name: 'Evening Snack', time: '05:30 PM', items: ['2 Brown Bread slices with Peanut Butter'], calories: 300, completed: false },
      { name: 'Dinner', time: '08:30 PM', items: ['200g Fish / Soya chunks', 'Mixed Veggies', '1 Chapati'], calories: 500, completed: false },
    ],
  },
]

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq_01',
    gym_id: 'gym_01',
    name: 'Commercial Treadmill X9',
    brand: 'LifeFitness',
    model: 'LF-9000',
    purchase_date: '2024-01-15',
    cost_paise: 28000000, // ₹2,80,000
    warranty_expiry: '2027-01-15',
    next_maintenance: '2026-10-15',
    status: 'active',
    location: 'Cardio Zone 1',
  },
  {
    id: 'eq_02',
    gym_id: 'gym_01',
    name: 'Olympic Smith Machine',
    brand: 'Hammer Strength',
    model: 'HS-SM-01',
    purchase_date: '2024-02-01',
    cost_paise: 19000000, // ₹1,90,000
    warranty_expiry: '2027-02-01',
    next_maintenance: '2026-11-01',
    status: 'active',
    location: 'Free Weights Area',
  },
  {
    id: 'eq_03',
    gym_id: 'gym_01',
    name: 'Dual Cable Cross Machine',
    brand: 'Matrix Fitness',
    model: 'G3-MS20',
    purchase_date: '2024-03-10',
    cost_paise: 32000000,
    warranty_expiry: '2027-03-10',
    next_maintenance: '2026-09-30', // Maintenance coming up
    status: 'maintenance',
    location: 'Cable Station',
  },
]

export const INITIAL_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'auto_01',
    gym_id: 'gym_01',
    name: 'Membership Expiry Alert (3 Days Before)',
    trigger: 'membership_expires_3_days',
    condition: 'Membership active and days_remaining = 3',
    action_channel: 'in_app',
    template: 'Dear {{member_name}}, your {{membership_name}} at {{gym_name}} expires on {{expiry_date}}. Renew today to enjoy uninterrupted fitness!',
    enabled: true,
  },
  {
    id: 'auto_02',
    gym_id: 'gym_01',
    name: 'Payment Due Overdue Reminder',
    trigger: 'payment_overdue',
    condition: 'Payment status is partial or pending and due > 0',
    action_channel: 'whatsapp',
    template: 'Hi {{member_name}}, your payment of ₹{{amount_due}} for {{gym_name}} is pending. Click here to pay online.',
    enabled: true,
  },
  {
    id: 'auto_03',
    gym_id: 'gym_01',
    name: 'Inactive Member Alert (7 Days Absent)',
    trigger: 'member_absent_7_days',
    condition: 'No attendance scan in past 7 days',
    action_channel: 'in_app',
    template: 'We miss you at {{gym_name}}, {{member_name}}! Your trainer {{trainer_name}} is ready for your next session.',
    enabled: true,
  },
]

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_01',
    gym_id: 'gym_01',
    user_name: 'Rahul Sharma (Owner)',
    action: 'GYM_SETTINGS_UPDATED',
    entity: 'Gym',
    entity_id: 'gym_01',
    timestamp: '2026-09-24T10:00:00Z',
    details: 'Updated GSTIN and primary brand colors.',
  },
  {
    id: 'audit_02',
    gym_id: 'gym_01',
    user_name: 'Neha Gupta (Receptionist)',
    action: 'MEMBER_CHECK_IN',
    entity: 'Member',
    entity_id: 'mem_01',
    timestamp: '2026-09-24T07:15:00Z',
    details: 'Recorded QR Check-in for Amit Verma.',
  },
  {
    id: 'audit_03',
    gym_id: 'gym_01',
    user_name: 'Neha Gupta (Receptionist)',
    action: 'PAYMENT_RECORDED',
    entity: 'Payment',
    entity_id: 'pay_01',
    timestamp: '2026-01-10T10:05:00Z',
    details: 'Collected ₹22,418.82 for Invoice TPFZ/2026-27/0001.',
  },
]
